// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mijwucgttegglnmyipax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pand1Y2d0dGVnZ2xubXlpcGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MjIzMDIsImV4cCI6MjA2NjA5ODMwMn0.oHPhIRworWvtCvhcCLK6ixBefz3Kwdvzh2ViCYMvJ9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);